services:
  slurm:
    # image: rocky8-slurm-hpci:latest
    build:
      context: .
      dockerfile: Dockerfile.slurm
    # entrypoint: ["/usr/bin/tini", "--"]
    # command:
    #   - "/bin/sh"
    #   - "-c"
    #   - "/usr/local/bin/start-ssh.sh && exec /usr/local/sbin/entrypoint.sh tail -f /dev/null"
    hostname: slurm
    container_name: slurm
    platform: linux/amd64
    volumes:
      - ./cgroup.conf:/etc/slurm/cgroup.conf
      - ../test_key.pub:/tmp/authorized_keys:ro
    ports:
      - "2223:22"

  pbs:
    image: australia-southeast1-docker.pkg.dev/nci-automation/docker/pbs:latest
    hostname: pbs
    container_name: pbs
    platform: linux/amd64
    ports:
      - "2222:22"
    depends_on:
      - slurm
    volumes:
      - ../test_key.pub:/tmp/authorized_keys:ro
