services:
  slurm:
    image: ghcr.io/garvan-data-science-platform/slurm:latest
    hostname: slurm
    container_name: slurm
    platform: linux/amd64
    volumes:
      - ./slurm/cgroup.conf:/etc/slurm/cgroup.conf
      - ./slurm/slurm.conf:/etc/slurm/slurm.conf
      - ../test_key.pub:/tmp/authorized_keys:ro
    ports:
      - "2223:22"

  pbs:
    image: ghcr.io/garvan-data-science-platform/pbs:latest
    hostname: pbs
    container_name: pbs
    platform: linux/amd64
    ports:
      - "2222:22"
    depends_on:
      - slurm
    volumes:
      - ../test_key.pub:/tmp/authorized_keys:ro
